Refactor
Kentico/Ksharp-parser pull request #3
Opened 2018-06-27 10:21 UTC by manhhungtran

Initial cleanup pull request

2018-06-28 14:00 UTC, PetrSvirak requested changes
Nice touch. I like how you get into the code 😃 

There is quite a number of commits though – some of them are really small. Feel free to rebase commits in a branch with opened PR and cosider squashing some of them together (you can write expressive message to 3rd and following lines of the commit message).

I still lack folder-based namespaces as well – that would surely be quick ([R# to the rescue](https://www.jetbrains.com/help/resharper/Refactorings__Adjust_Namespaces.html)).

Last but not least, there are some question below (see the outdated comments, please).

2018-06-28 14:00 UTC, PetrSvirak commented on KSharp/KSharpParser/Integration/KSharpVisitor.cs
> -        #region "High level structure expressions"
I hate regions as well, however, this is still 1500 lines long file and I believe that simple removal does not solve the problem. Do you plan to move private methods to some new dependency classes or something like that?

2018-06-28 14:00 UTC, PetrSvirak commented on KSharp/KSharpParser/Integration/KSharpVisitor.cs
> +                    ++value;
Just out of curiosity: what exactly brings this change? 👀

2018-06-28 14:00 UTC, PetrSvirak commented on KSharp/KSharpParser/Integration/KSharpVisitor.cs
> +            if ((operationType != OperatorTypeEnum.ASSIGN) && (variableOriginalValue == null))
Does this ever happen? (since there is [the line 662](https://github.com/Kentico/Ksharp-parser/pull/3/commits/4e601d69078ca03b3a960803452e2c859f5658a2#diff-83e5bac2a120607b5cec60ff8f3503dfR662) just a bit above)
Would it, for example, be possible to throw the exception earlier?

2018-06-28 14:00 UTC, PetrSvirak commented on KSharp/KSharpParser/Integration/KSharpVisitor.cs
> +            return (item is string itemString) && !itemString.Contains("\"");
👍

2018-06-28 14:42 UTC, manhhungtran commented on KSharp/KSharpParser/Integration/KSharpVisitor.cs
> +                    ++value;
Although it would not change the behavior, I've been always told to use this syntax for making CPU happy. And I like it more 🗡 .

2018-06-28 14:47 UTC, manhhungtran commented on KSharp/KSharpParser/Integration/KSharpVisitor.cs
> -        #region "High level structure expressions"
Yes, I'm planning to split this huge class in the future. This will be done in separated task :)

2018-06-28 15:31 UTC, PetrSvirak commented on KSharp/KSharpParser/Integration/KSharpVisitor.cs
> +                    ++value;
It is not true even for C(++), I believe. Have a look at this [SOa](https://stackoverflow.com/a/24904/1138663) and there is a significantly more clever compiler [in C# ([SO])](https://stackoverflow.com/questions/6075452/c-sharp-generated-il-for-operator-when-and-why-prefix-postfix-notation-is-f). However, liking this syntax more is a valid point in this case – just as I said, I was only curious.

2018-07-27 15:03 UTC, manhhungtran commented
Commits were squished and all comments processed. Feel free to review

2018-07-27 16:08 UTC, PetrSvirak approved these changes

2018-07-27 16:14 UTC, merged